# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200, verbose_name='Application Name')),
                ('app_data_path', models.CharField(max_length=200, verbose_name='Data Path')),
            ],
        ),
        migrations.CreateModel(
            name='WayPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.CharField(max_length=32, verbose_name='Point Name')),
                ('point_lat', models.FloatField(verbose_name='Point Latitude')),
                ('point_lng', models.FloatField(verbose_name='Point Longitude')),
                ('point_time', models.DateTimeField(verbose_name='Point Time')),
                ('app_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twpoint.Application')),
            ],
        ),
    ]
