# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=200, verbose_name='Application Name')),
                ('app_package', models.CharField(max_length=200, verbose_name='Data Path')),
            ],
        ),
        migrations.CreateModel(
            name='BaseStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('lng', models.FloatField(verbose_name='Longitude')),
                ('sender', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('time', models.IntegerField()),
                ('device', models.CharField(max_length=255)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('md5', models.CharField(max_length=32)),
                ('sha1', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='WayPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, null=True)),
                ('table_name', models.CharField(max_length=255, null=True)),
                ('point_time', models.DateTimeField(null=True, verbose_name='Point Time')),
                ('position', models.CharField(max_length=255, null=True)),
                ('position_x', models.CharField(max_length=255, null=True)),
                ('position_y', models.CharField(max_length=255, null=True)),
                ('start', models.CharField(max_length=255, null=True)),
                ('start_x', models.CharField(max_length=255, null=True)),
                ('start_y', models.CharField(max_length=255, null=True)),
                ('end', models.CharField(max_length=255, null=True)),
                ('end_x', models.CharField(max_length=255, null=True)),
                ('end_y', models.CharField(max_length=255, null=True)),
                ('search', models.CharField(max_length=255, null=True)),
                ('search_x', models.CharField(max_length=255, null=True)),
                ('search_y', models.CharField(max_length=255, null=True)),
                ('app_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twpoint.Application')),
            ],
        ),
    ]
