# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twpoint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='point_time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
