# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twpoint', '0002_auto_20161201_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('case_no', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
