# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twpoint', '0003_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='case_no',
            field=models.IntegerField(),
        ),
    ]
