# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twpoint', '0004_auto_20161201_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basestation',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
