# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-01 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twpoint', '0005_auto_20161201_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='case_no',
            field=models.CharField(max_length=255),
        ),
    ]
