# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twpoint', '0006_auto_20161201_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='statics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
                ('level', models.IntegerField()),
                ('pid', models.IntegerField()),
            ],
        ),
    ]
